[Desktop Entry]
Type=X-GNOME-Metatheme
Name=04-Crunchy-grey_SQ
Comment=Variant of Ambiance theme
Encoding=UTF-8

[X-GNOME-Metatheme]
GtkTheme=04-Crunchy-grey
MetacityTheme=04-Crunchy-grey_SQ
GtkColorScheme=base_color:#FAFAFA,fg_color:#4c4c4c,tooltip_fg_color:white,selected_bg_color:#f07746,selected_fg_color:white,text_color:#3C3C3C,bg_color:#F2F1F2,tooltip_bg_color:#373b3c,link_color:#f07746,light_grey:#cdcdcd
IconTheme=Humanity-Dark
CursorTheme=default
ButtonLayout=close,minimize,maximize:
